spring:
  application:
    name: ai-springboot

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/mental_health_assistant?useSSL=false&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD}

## 服务器配置
server:
  port: 1234